/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description User Account Details. */
        Account: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /** @example John Doe */
            name: string;
            /**
             * Format: email
             * @example john@example.com
             */
            email: string;
        };
        /** @description User account filtering/searching options. */
        AccountFilter: {
            /** @example John Doe */
            name?: string;
        };
        /** @description A group chat/server of users. */
        Group: {
            /**
             * Format: uuid
             * @example
             */
            id: string;
            /** @example Testing Group */
            name: string;
            /** @example This is a testing group. */
            description: string;
            /** @example [
             *       "550e8400-e29b-41d4-a716-446655440000"
             *     ] */
            members: string[];
        };
        /** @description Group filtering/searching options. */
        GroupFilter: {
            /** @example Testing Group */
            name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
