/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root Endpoint */
        get: operations["GetRoot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Account details to add. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            responses: {
                /** @description Account creation successful. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account By ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of account to get. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account with specified ID. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
            };
        };
        /** Update Account By ID */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of account to update. */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Account details to add. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            responses: {
                /** @description Updated account with specified ID. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
            };
        };
        post?: never;
        /** Delete Account By ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of account to delete. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account was deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search for accounts satisfying various properties. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Account searching parameters. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountFilter"];
                };
            };
            responses: {
                /** @description Query completed successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/group/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a group */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Group details to add. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            responses: {
                /** @description Group creation successful. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Group"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/group/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search for groups satisfying various properties. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Group searching parameters. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GroupFilter"];
                };
            };
            responses: {
                /** @description Query completed successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Group"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/group/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Group By ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of group to get. */
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Group with specified ID. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Group"];
                    };
                };
            };
        };
        /** Update Group By ID */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of group to update. */
                    groupId: string;
                };
                cookie?: never;
            };
            /** @description Group details to add. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            responses: {
                /** @description Updated group with specified ID. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Group"];
                    };
                };
            };
        };
        post?: never;
        /** Delete Group By ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of group to delete. */
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Group was deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/group/{groupId}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add new member to a group */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of group to add member to. */
                    groupId: string;
                    /** @description ID of member to add. */
                    memberId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        /** Remove member from a group */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of group to remove member from. */
                    groupId: string;
                    /** @description ID of member to remove. */
                    memberId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description User Account Details. */
        Account: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /** Format: date-time */
            created_at?: string;
            /** @example John Doe */
            username: string;
            /** Format: base64 */
            profile_pic: string;
        };
        /** @description A group chat/server of users. */
        Group: {
            /**
             * Format: uuid
             * @example
             */
            id: string;
            /** Format: date-time */
            created_at?: string;
            /** @example Testing Group */
            name: string;
            /** @example This is a testing group. */
            description: string;
            /** @example [
             *       "550e8400-e29b-41d4-a716-446655440000"
             *     ] */
            members: string[];
            channels: string[];
        };
        /** @description A set of messages within a Group, typically organized by topic. */
        Channel: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at?: string;
            /** @example Main */
            name: string;
            /** @example General conversations go here. */
            description?: string;
            messages: string[];
            pinned_messages: string[];
        };
        /** @description A message that is sent in a group. */
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: uuid */
            author: string;
            body: string;
        };
        /** @description An object that is posted to the backend to query for accounts based on filter criteria. */
        AccountFilter: {
            /** @description Get accounts that have an id within this list of ids. */
            ids?: string[];
            /**
             * Format: date-time
             * @description Get accounts created from this date.
             */
            from?: string;
            /**
             * Format: date-time
             * @description Get accounts created from this date.
             */
            until?: string;
            /** @description Get accounts that (fuzzily) match the provided username. */
            username?: string;
        };
        /** @description An object that is posted to the backend to query for groups based on filter criteria. */
        GroupFilter: {
            id?: string[];
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            until?: string;
            /** @example Testing */
            name?: string;
        };
        /** @description An object that is posted to the backend to query for channels based on filter criteria. */
        ChannelFilter: {
            id?: string[];
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            until?: string;
            /** @example Main */
            name?: string;
        };
        /** @description An object that is posted to the backend to query for messages based on filter criteria. */
        MessageFilter: {
            id?: string[];
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            until?: string;
            /** Format: uuid */
            author?: string;
            body?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetRoot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
