# Define the schemas for the structs.
openapi: 3.0.0
info:
  title: Sector
  version: 1.0.0
  description: The Rest-like API for the Sector application.
  servers:
  - url: /v1/api

paths:
  "/":
    get:
      summary: Root Endpoint
      operationId: GetRoot
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
  "/health":
    get:
      summary: Health Check
      operationId: GetHealth
      responses:
        "200":
          description: API is healthy
          content:
            text/plain:
              schema:
                type: string
  "/account/{id}":
    get: 
      summary: Get Account By ID
      operationID: GetAccountByID
      parameters:
        - in: path
          name: id
          description: ID of account to get.
          required: true
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      responses: 
        "200":
          description: Account with specified ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    delete:
      summary: Delete Account By ID
      operationID: DeleteAccountByID
      parameters:
        - in: path
          name: id
          description: ID of account to get.
          required: true
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      responses: 
        "200":
          description: Account was deleted.
          content:
            text/plain:
              schema:
                type: string
    # TODO: PUT/POST request at this endpoint for updating or creating an account.

  # TODO: below should be a route that takes a POST request of AccountFilter object and returns a list of accounts that satisfies the request 
  #       maybe we paginate the response? maybe not.
  #"/account/search":
  #  post: 

  # TODO: similar endpoints to above for groups and other data types.

components:
  schemas:
    Account:
      description: User Account Details.
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        created_at: 
          type: string
          format: date-time
        username:
          type: string
          example: John Doe
        profile_pic: 
          type: string
          format: binary
      required: 
        - id
        - username
        - profile_pic

    Group:
      description: A group chat/server of users.
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: ""
        created_at: 
          type: string
          format: date-time
        name: 
          type: string
          example: Testing Group
        description: 
          type: string
          example: This is a testing group. 
        members:
          type: array
          items:
            type: string
          example: ["550e8400-e29b-41d4-a716-446655440000"]
        channels:
          type: array
          items:
            type: string
          
      required: 
        - id
        - name
        - description
        - members
        - channels

    GroupFilter:
      description: Group filtering/searching options.
      type: object
      properties:
        name: 
          type: string
          example: Testing Group