name: Backend Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        working-directory: ./backend
        run: go get .

      - name: Build
        working-directory: ./backend
        run: go build -v ./...
      
      - name: Test with the Go CLI
        working-directory: ./backend
        run: go test
