name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      
      - name: Install dependencies
        working-directory: ./Sector
        run: go get .

      - name: Build Wails
        working-directory: ./Sector
        run: wails build
